### ISSUE TITLE
`attohttpc` is a thread-blocking HTTP client

### ISSUE THREAD

**Issue by thomaseizinger** [dariusc93/rust-igd#3]
As far as I understand, https://docs.rs/attohttpc is a blocking HTTP client and doesn't use `async`. Now that we have integration with two runtimes, we should probably use an `async` client or `hyper` directly.

See https://github.com/dariusc93/rust-igd/blob/master/src/gateway.rs#L28-L32.

**Comment by jxs** [comment]
can we feature gate the whole blocking mod? If you want to make it non (or less) breaking you can add it to the `default-features`

**Comment by thomaseizinger** [comment]
Ah, I had no idea this code was duplicated with the non-blocking mode! Yeah feature-gating would be ideal to reduce our dependency tree :)

**Comment by jxs** [comment]
> Ah, I had no idea this code was duplicated with the non-blocking mode! Yeah feature-gating would be ideal to reduce our dependency tree :)

yeah we are using [`aio::gateway`](https://github.com/dariusc93/rust-igd/blob/master/src/aio/gateway.rs#L14) :)

**Comment by thomaseizinger** [comment]
Nice! I guess this issue can be seen as implementing the feature flag then :)
