### ISSUE TITLE
Upgrade to hyper 1.0

### ISSUE THREAD

**Issue by stormshield-kg** [dariusc93/rust-igd#4]

**Comment by dariusc93** [comment]
Hi! Sorry for the late response and thank you for the suggestion. Did not know they have reached 1.0 so I will probably look into this very soon. Of course any and contributions are welcome :)

**Comment by DaniPopes** [comment]
Hi, any updates?

**Comment by dariusc93** [comment]
Hey @DaniPopes. I havent gotten to it yet (been reading over the docs of the changes) but should be getting to it soon. If you would like to take up on updating hyper you are more than welcome to as well :)
